# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/juju/mem_io_unit_testing/mem_io_unit_testing.srcs/sources_1/bd/design_1/ip/design_1_mem_hw_0_1/design_1_mem_hw_0_1.xci
# IP: The module: 'design_1_mem_hw_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/juju/mem_io_unit_testing/mem_io_unit_testing.srcs/sources_1/bd/design_1/ip/design_1_mem_hw_0_1/constraints/mem_hw_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mem_hw_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/juju/mem_io_unit_testing/mem_io_unit_testing.srcs/sources_1/bd/design_1/ip/design_1_mem_hw_0_1/design_1_mem_hw_0_1.xci
# IP: The module: 'design_1_mem_hw_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/juju/mem_io_unit_testing/mem_io_unit_testing.srcs/sources_1/bd/design_1/ip/design_1_mem_hw_0_1/constraints/mem_hw_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mem_hw_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
