// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================


extern void AESL_WRAP_mem_hw (
hls::stream<struct ap_axiu<32, 1, 1, 1 > > (&out),
hls::stream<struct ap_axiu<32, 1, 1, 1 > > (&in),
int rw,
long unsigned int mask,
ap_uint<32> test_init_arr[512]);

