// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xmem_hw.h"

extern XMem_hw_Config XMem_hw_ConfigTable[];

XMem_hw_Config *XMem_hw_LookupConfig(u16 DeviceId) {
	XMem_hw_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XMEM_HW_NUM_INSTANCES; Index++) {
		if (XMem_hw_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XMem_hw_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XMem_hw_Initialize(XMem_hw *InstancePtr, u16 DeviceId) {
	XMem_hw_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XMem_hw_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XMem_hw_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

