// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

 `timescale 1ns/1ps


`define AUTOTB_DUT      mem_hw
`define AUTOTB_DUT_INST AESL_inst_mem_hw
`define AUTOTB_TOP      apatb_mem_hw_top
`define AUTOTB_LAT_RESULT_FILE "mem_hw.result.lat.rb"
`define AUTOTB_PER_RESULT_TRANS_FILE "mem_hw.performance.result.transaction.xml"
`define AUTOTB_TOP_INST AESL_inst_apatb_mem_hw_top
`define AUTOTB_MAX_ALLOW_LATENCY  15000000
`define AUTOTB_CLOCK_PERIOD_DIV2 400.00

`define AESL_DEPTH_out_V_data_V 1
`define AESL_DEPTH_out_V_keep_V 1
`define AESL_DEPTH_out_V_strb_V 1
`define AESL_DEPTH_out_V_user_V 1
`define AESL_DEPTH_out_V_last_V 1
`define AESL_DEPTH_out_V_id_V 1
`define AESL_DEPTH_out_V_dest_V 1
`define AESL_DEPTH_in_V_data_V 1
`define AESL_DEPTH_in_V_keep_V 1
`define AESL_DEPTH_in_V_strb_V 1
`define AESL_DEPTH_in_V_user_V 1
`define AESL_DEPTH_in_V_last_V 1
`define AESL_DEPTH_in_V_id_V 1
`define AESL_DEPTH_in_V_dest_V 1
`define AESL_DEPTH_rw 1
`define AESL_DEPTH_mask 1
`define AESL_DEPTH_test_init_arr_V 1
`define AUTOTB_TVIN_out_V_data_V  "../tv/cdatafile/c.mem_hw.autotvin_out_V_data_V.dat"
`define AUTOTB_TVIN_out_V_keep_V  "../tv/cdatafile/c.mem_hw.autotvin_out_V_keep_V.dat"
`define AUTOTB_TVIN_out_V_strb_V  "../tv/cdatafile/c.mem_hw.autotvin_out_V_strb_V.dat"
`define AUTOTB_TVIN_out_V_user_V  "../tv/cdatafile/c.mem_hw.autotvin_out_V_user_V.dat"
`define AUTOTB_TVIN_out_V_last_V  "../tv/cdatafile/c.mem_hw.autotvin_out_V_last_V.dat"
`define AUTOTB_TVIN_out_V_id_V  "../tv/cdatafile/c.mem_hw.autotvin_out_V_id_V.dat"
`define AUTOTB_TVIN_out_V_dest_V  "../tv/cdatafile/c.mem_hw.autotvin_out_V_dest_V.dat"
`define AUTOTB_TVIN_in_V_data_V  "../tv/cdatafile/c.mem_hw.autotvin_in_V_data_V.dat"
`define AUTOTB_TVIN_in_V_keep_V  "../tv/cdatafile/c.mem_hw.autotvin_in_V_keep_V.dat"
`define AUTOTB_TVIN_in_V_strb_V  "../tv/cdatafile/c.mem_hw.autotvin_in_V_strb_V.dat"
`define AUTOTB_TVIN_in_V_user_V  "../tv/cdatafile/c.mem_hw.autotvin_in_V_user_V.dat"
`define AUTOTB_TVIN_in_V_last_V  "../tv/cdatafile/c.mem_hw.autotvin_in_V_last_V.dat"
`define AUTOTB_TVIN_in_V_id_V  "../tv/cdatafile/c.mem_hw.autotvin_in_V_id_V.dat"
`define AUTOTB_TVIN_in_V_dest_V  "../tv/cdatafile/c.mem_hw.autotvin_in_V_dest_V.dat"
`define AUTOTB_TVIN_test_init_arr_V  "../tv/cdatafile/c.mem_hw.autotvin_test_init_arr_V.dat"
`define AUTOTB_TVIN_out_V_data_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvin_out_V_data_V.dat"
`define AUTOTB_TVIN_out_V_keep_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvin_out_V_keep_V.dat"
`define AUTOTB_TVIN_out_V_strb_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvin_out_V_strb_V.dat"
`define AUTOTB_TVIN_out_V_user_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvin_out_V_user_V.dat"
`define AUTOTB_TVIN_out_V_last_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvin_out_V_last_V.dat"
`define AUTOTB_TVIN_out_V_id_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvin_out_V_id_V.dat"
`define AUTOTB_TVIN_out_V_dest_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvin_out_V_dest_V.dat"
`define AUTOTB_TVIN_in_V_data_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvin_in_V_data_V.dat"
`define AUTOTB_TVIN_in_V_keep_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvin_in_V_keep_V.dat"
`define AUTOTB_TVIN_in_V_strb_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvin_in_V_strb_V.dat"
`define AUTOTB_TVIN_in_V_user_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvin_in_V_user_V.dat"
`define AUTOTB_TVIN_in_V_last_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvin_in_V_last_V.dat"
`define AUTOTB_TVIN_in_V_id_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvin_in_V_id_V.dat"
`define AUTOTB_TVIN_in_V_dest_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvin_in_V_dest_V.dat"
`define AUTOTB_TVIN_test_init_arr_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvin_test_init_arr_V.dat"
`define AUTOTB_TVOUT_out_V_data_V  "../tv/cdatafile/c.mem_hw.autotvout_out_V_data_V.dat"
`define AUTOTB_TVOUT_out_V_keep_V  "../tv/cdatafile/c.mem_hw.autotvout_out_V_keep_V.dat"
`define AUTOTB_TVOUT_out_V_strb_V  "../tv/cdatafile/c.mem_hw.autotvout_out_V_strb_V.dat"
`define AUTOTB_TVOUT_out_V_user_V  "../tv/cdatafile/c.mem_hw.autotvout_out_V_user_V.dat"
`define AUTOTB_TVOUT_out_V_last_V  "../tv/cdatafile/c.mem_hw.autotvout_out_V_last_V.dat"
`define AUTOTB_TVOUT_out_V_id_V  "../tv/cdatafile/c.mem_hw.autotvout_out_V_id_V.dat"
`define AUTOTB_TVOUT_out_V_dest_V  "../tv/cdatafile/c.mem_hw.autotvout_out_V_dest_V.dat"
`define AUTOTB_TVOUT_out_V_data_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvout_out_V_data_V.dat"
`define AUTOTB_TVOUT_out_V_keep_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvout_out_V_keep_V.dat"
`define AUTOTB_TVOUT_out_V_strb_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvout_out_V_strb_V.dat"
`define AUTOTB_TVOUT_out_V_user_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvout_out_V_user_V.dat"
`define AUTOTB_TVOUT_out_V_last_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvout_out_V_last_V.dat"
`define AUTOTB_TVOUT_out_V_id_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvout_out_V_id_V.dat"
`define AUTOTB_TVOUT_out_V_dest_V_out_wrapc  "../tv/rtldatafile/rtl.mem_hw.autotvout_out_V_dest_V.dat"
module `AUTOTB_TOP;

parameter AUTOTB_TRANSACTION_NUM = 2;
parameter PROGRESS_TIMEOUT = 10000000;
parameter LATENCY_ESTIMATION = 8388099;
parameter LENGTH_out_V_data_V = 8388096;
parameter LENGTH_out_V_keep_V = 8388096;
parameter LENGTH_out_V_strb_V = 8388096;
parameter LENGTH_out_V_user_V = 8388096;
parameter LENGTH_out_V_last_V = 8388096;
parameter LENGTH_out_V_id_V = 8388096;
parameter LENGTH_out_V_dest_V = 8388096;
parameter LENGTH_in_V_data_V = 8388096;
parameter LENGTH_in_V_keep_V = 8388096;
parameter LENGTH_in_V_strb_V = 8388096;
parameter LENGTH_in_V_user_V = 8388096;
parameter LENGTH_in_V_last_V = 8388096;
parameter LENGTH_in_V_id_V = 8388096;
parameter LENGTH_in_V_dest_V = 8388096;
parameter LENGTH_test_init_arr_V = 512;

task read_token;
    input integer fp;
    output reg [223 : 0] token;
    integer ret;
    begin
        token = "";
        ret = 0;
        ret = $fscanf(fp,"%s",token);
    end
endtask

reg AESL_clock;
reg rst;
reg start;
reg ce;
reg tb_continue;
wire AESL_start;
wire AESL_reset;
wire AESL_ce;
wire AESL_ready;
wire AESL_idle;
wire AESL_continue;
wire AESL_done;
reg AESL_done_delay = 0;
reg AESL_done_delay2 = 0;
reg AESL_ready_delay = 0;
wire ready;
wire ready_wire;
wire [11 : 0] CONTROL_BUS_AWADDR;
wire  CONTROL_BUS_AWVALID;
wire  CONTROL_BUS_AWREADY;
wire  CONTROL_BUS_WVALID;
wire  CONTROL_BUS_WREADY;
wire [31 : 0] CONTROL_BUS_WDATA;
wire [3 : 0] CONTROL_BUS_WSTRB;
wire [11 : 0] CONTROL_BUS_ARADDR;
wire  CONTROL_BUS_ARVALID;
wire  CONTROL_BUS_ARREADY;
wire  CONTROL_BUS_RVALID;
wire  CONTROL_BUS_RREADY;
wire [31 : 0] CONTROL_BUS_RDATA;
wire [1 : 0] CONTROL_BUS_RRESP;
wire  CONTROL_BUS_BVALID;
wire  CONTROL_BUS_BREADY;
wire [1 : 0] CONTROL_BUS_BRESP;
wire  CONTROL_BUS_INTERRUPT;
wire [31 : 0] out_r_TDATA;
wire [3 : 0] out_r_TKEEP;
wire [3 : 0] out_r_TSTRB;
wire [0 : 0] out_r_TUSER;
wire [0 : 0] out_r_TLAST;
wire [0 : 0] out_r_TID;
wire [0 : 0] out_r_TDEST;
wire [31 : 0] in_r_TDATA;
wire [3 : 0] in_r_TKEEP;
wire [3 : 0] in_r_TSTRB;
wire [0 : 0] in_r_TUSER;
wire [0 : 0] in_r_TLAST;
wire [0 : 0] in_r_TID;
wire [0 : 0] in_r_TDEST;
wire  in_r_TVALID;
wire  in_r_TREADY;
wire  out_r_TVALID;
wire  out_r_TREADY;
integer done_cnt = 0;
integer AESL_ready_cnt = 0;
integer ready_cnt = 0;
reg ready_initial;
reg ready_initial_n;
reg ready_last_n;
reg ready_delay_last_n;
reg done_delay_last_n;
reg interface_done = 0;
wire CONTROL_BUS_write_data_finish;
wire AESL_slave_start;
wire AESL_slave_write_start_in;
wire AESL_slave_write_start_finish;
reg AESL_slave_ready;
wire AESL_slave_output_done;
reg ready_rise = 0;
reg start_rise = 0;
reg slave_start_status = 0;
reg slave_done_status = 0;

wire ap_clk;
wire ap_rst_n;
wire ap_rst_n_n;

`AUTOTB_DUT `AUTOTB_DUT_INST(
    .s_axi_CONTROL_BUS_AWADDR(CONTROL_BUS_AWADDR),
    .s_axi_CONTROL_BUS_AWVALID(CONTROL_BUS_AWVALID),
    .s_axi_CONTROL_BUS_AWREADY(CONTROL_BUS_AWREADY),
    .s_axi_CONTROL_BUS_WVALID(CONTROL_BUS_WVALID),
    .s_axi_CONTROL_BUS_WREADY(CONTROL_BUS_WREADY),
    .s_axi_CONTROL_BUS_WDATA(CONTROL_BUS_WDATA),
    .s_axi_CONTROL_BUS_WSTRB(CONTROL_BUS_WSTRB),
    .s_axi_CONTROL_BUS_ARADDR(CONTROL_BUS_ARADDR),
    .s_axi_CONTROL_BUS_ARVALID(CONTROL_BUS_ARVALID),
    .s_axi_CONTROL_BUS_ARREADY(CONTROL_BUS_ARREADY),
    .s_axi_CONTROL_BUS_RVALID(CONTROL_BUS_RVALID),
    .s_axi_CONTROL_BUS_RREADY(CONTROL_BUS_RREADY),
    .s_axi_CONTROL_BUS_RDATA(CONTROL_BUS_RDATA),
    .s_axi_CONTROL_BUS_RRESP(CONTROL_BUS_RRESP),
    .s_axi_CONTROL_BUS_BVALID(CONTROL_BUS_BVALID),
    .s_axi_CONTROL_BUS_BREADY(CONTROL_BUS_BREADY),
    .s_axi_CONTROL_BUS_BRESP(CONTROL_BUS_BRESP),
    .interrupt(CONTROL_BUS_INTERRUPT),
    .ap_clk(ap_clk),
    .ap_rst_n(ap_rst_n),
    .out_r_TDATA(out_r_TDATA),
    .out_r_TKEEP(out_r_TKEEP),
    .out_r_TSTRB(out_r_TSTRB),
    .out_r_TUSER(out_r_TUSER),
    .out_r_TLAST(out_r_TLAST),
    .out_r_TID(out_r_TID),
    .out_r_TDEST(out_r_TDEST),
    .in_r_TDATA(in_r_TDATA),
    .in_r_TKEEP(in_r_TKEEP),
    .in_r_TSTRB(in_r_TSTRB),
    .in_r_TUSER(in_r_TUSER),
    .in_r_TLAST(in_r_TLAST),
    .in_r_TID(in_r_TID),
    .in_r_TDEST(in_r_TDEST),
    .in_r_TVALID(in_r_TVALID),
    .in_r_TREADY(in_r_TREADY),
    .out_r_TVALID(out_r_TVALID),
    .out_r_TREADY(out_r_TREADY));

// Assignment for control signal
assign ap_clk = AESL_clock;
assign ap_rst_n = AESL_reset;
assign ap_rst_n_n = ~AESL_reset;
assign AESL_reset = rst;
assign AESL_start = start;
assign AESL_ce = ce;
assign AESL_continue = tb_continue;
  assign AESL_slave_write_start_in = slave_start_status  & CONTROL_BUS_write_data_finish;
  assign AESL_slave_start = AESL_slave_write_start_finish;
  assign AESL_done = slave_done_status ;

always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
    begin
        slave_start_status <= 1;
    end
    else begin
        if (AESL_start == 1 ) begin
            start_rise = 1;
        end
        if (start_rise == 1 && AESL_done == 1 ) begin
            slave_start_status <= 1;
        end
        if (AESL_slave_write_start_in == 1) begin 
            slave_start_status <= 0;
            start_rise = 0;
        end
    end
end

always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
    begin
        AESL_slave_ready <= 0;
        ready_rise = 0;
    end
    else begin
        if (AESL_ready == 1 ) begin
            ready_rise = 1;
        end
        if (ready_rise == 1 && AESL_done_delay == 1 ) begin
            AESL_slave_ready <= 1;
        end
        if (AESL_slave_ready == 1) begin 
            AESL_slave_ready <= 0;
            ready_rise = 0;
        end
    end
end

always @ (posedge AESL_clock)
begin
    if (AESL_done == 1) begin
        slave_done_status <= 0;
    end
    else if (AESL_slave_output_done == 1 ) begin
        slave_done_status <= 1;
    end
end

















reg [31:0] ap_c_n_tvin_trans_num_out_V_data_V;

reg out_r_ready_reg; // for self-sync

wire out_r_ready;
wire out_r_done;
wire [31:0] out_r_transaction;
wire axi_s_out_r_TVALID;
wire axi_s_out_r_TREADY;

AESL_axi_s_out_r AESL_AXI_S_out_r(
    .clk(AESL_clock),
    .reset(AESL_reset),
    .TRAN_out_r_TDATA(out_r_TDATA),
    .TRAN_out_r_TKEEP(out_r_TKEEP),
    .TRAN_out_r_TSTRB(out_r_TSTRB),
    .TRAN_out_r_TUSER(out_r_TUSER),
    .TRAN_out_r_TLAST(out_r_TLAST),
    .TRAN_out_r_TID(out_r_TID),
    .TRAN_out_r_TDEST(out_r_TDEST),
    .TRAN_out_r_TVALID(axi_s_out_r_TVALID),
    .TRAN_out_r_TREADY(axi_s_out_r_TREADY),
    .ready(out_r_ready),
    .done(out_r_done),
    .transaction(out_r_transaction));

assign out_r_ready = 0;
assign out_r_done = AESL_done;

assign axi_s_out_r_TVALID = out_r_TVALID;

reg reg_out_r_TREADY;
initial begin : gen_reg_out_r_TREADY_process
    integer proc_rand;
    reg_out_r_TREADY = axi_s_out_r_TREADY;
    while(1)
    begin
        @(axi_s_out_r_TREADY);
        reg_out_r_TREADY = axi_s_out_r_TREADY;
    end
end


assign out_r_TREADY = reg_out_r_TREADY;
reg [31:0] ap_c_n_tvin_trans_num_in_V_data_V;

reg in_r_ready_reg; // for self-sync

wire in_r_ready;
wire in_r_done;
wire [31:0] in_r_transaction;
wire axi_s_in_r_TVALID;
wire axi_s_in_r_TREADY;

AESL_axi_s_in_r AESL_AXI_S_in_r(
    .clk(AESL_clock),
    .reset(AESL_reset),
    .TRAN_in_r_TDATA(in_r_TDATA),
    .TRAN_in_r_TKEEP(in_r_TKEEP),
    .TRAN_in_r_TSTRB(in_r_TSTRB),
    .TRAN_in_r_TUSER(in_r_TUSER),
    .TRAN_in_r_TLAST(in_r_TLAST),
    .TRAN_in_r_TID(in_r_TID),
    .TRAN_in_r_TDEST(in_r_TDEST),
    .TRAN_in_r_TVALID(axi_s_in_r_TVALID),
    .TRAN_in_r_TREADY(axi_s_in_r_TREADY),
    .ready(in_r_ready),
    .done(in_r_done),
    .transaction(in_r_transaction));

assign in_r_ready = ready;
assign in_r_done = 0;

assign in_r_TVALID = axi_s_in_r_TVALID;

assign axi_s_in_r_TREADY = in_r_TREADY;

AESL_axi_slave_CONTROL_BUS AESL_AXI_SLAVE_CONTROL_BUS(
    .clk   (AESL_clock),
    .reset (AESL_reset),
    .TRAN_s_axi_CONTROL_BUS_AWADDR (CONTROL_BUS_AWADDR),
    .TRAN_s_axi_CONTROL_BUS_AWVALID (CONTROL_BUS_AWVALID),
    .TRAN_s_axi_CONTROL_BUS_AWREADY (CONTROL_BUS_AWREADY),
    .TRAN_s_axi_CONTROL_BUS_WVALID (CONTROL_BUS_WVALID),
    .TRAN_s_axi_CONTROL_BUS_WREADY (CONTROL_BUS_WREADY),
    .TRAN_s_axi_CONTROL_BUS_WDATA (CONTROL_BUS_WDATA),
    .TRAN_s_axi_CONTROL_BUS_WSTRB (CONTROL_BUS_WSTRB),
    .TRAN_s_axi_CONTROL_BUS_ARADDR (CONTROL_BUS_ARADDR),
    .TRAN_s_axi_CONTROL_BUS_ARVALID (CONTROL_BUS_ARVALID),
    .TRAN_s_axi_CONTROL_BUS_ARREADY (CONTROL_BUS_ARREADY),
    .TRAN_s_axi_CONTROL_BUS_RVALID (CONTROL_BUS_RVALID),
    .TRAN_s_axi_CONTROL_BUS_RREADY (CONTROL_BUS_RREADY),
    .TRAN_s_axi_CONTROL_BUS_RDATA (CONTROL_BUS_RDATA),
    .TRAN_s_axi_CONTROL_BUS_RRESP (CONTROL_BUS_RRESP),
    .TRAN_s_axi_CONTROL_BUS_BVALID (CONTROL_BUS_BVALID),
    .TRAN_s_axi_CONTROL_BUS_BREADY (CONTROL_BUS_BREADY),
    .TRAN_s_axi_CONTROL_BUS_BRESP (CONTROL_BUS_BRESP),
    .TRAN_CONTROL_BUS_interrupt (CONTROL_BUS_INTERRUPT),
    .TRAN_CONTROL_BUS_write_data_finish(CONTROL_BUS_write_data_finish),
    .TRAN_CONTROL_BUS_ready_out (AESL_ready),
    .TRAN_CONTROL_BUS_ready_in (AESL_slave_ready),
    .TRAN_CONTROL_BUS_done_out (AESL_slave_output_done),
    .TRAN_CONTROL_BUS_idle_out (AESL_idle),
    .TRAN_CONTROL_BUS_write_start_in     (AESL_slave_write_start_in),
    .TRAN_CONTROL_BUS_write_start_finish (AESL_slave_write_start_finish),
    .TRAN_CONTROL_BUS_transaction_done_in (AESL_done_delay),
    .TRAN_CONTROL_BUS_start_in  (AESL_slave_start)
);

initial begin : generate_AESL_ready_cnt_proc
    AESL_ready_cnt = 0;
    wait(AESL_reset === 1);
    while(AESL_ready_cnt != AUTOTB_TRANSACTION_NUM) begin
        while(AESL_ready !== 1) begin
            @(posedge AESL_clock);
            # 0.4;
        end
        @(negedge AESL_clock);
        AESL_ready_cnt = AESL_ready_cnt + 1;
        @(posedge AESL_clock);
        # 0.4;
    end
end

    event next_trigger_ready_cnt;
    
    initial begin : gen_ready_cnt
        ready_cnt = 0;
        wait (AESL_reset === 1);
        forever begin
            @ (posedge AESL_clock);
            if (ready == 1) begin
                if (ready_cnt < AUTOTB_TRANSACTION_NUM) begin
                    ready_cnt = ready_cnt + 1;
                end
            end
            -> next_trigger_ready_cnt;
        end
    end
    
    wire all_finish = (done_cnt == AUTOTB_TRANSACTION_NUM);
    
    // done_cnt
    always @ (posedge AESL_clock) begin
        if (~AESL_reset) begin
            done_cnt <= 0;
        end else begin
            if (AESL_done == 1) begin
                if (done_cnt < AUTOTB_TRANSACTION_NUM) begin
                    done_cnt <= done_cnt + 1;
                end
            end
        end
    end
    
    initial begin : finish_simulation
        wait (all_finish == 1);
        // last transaction is saved at negedge right after last done
        @ (posedge AESL_clock);
        @ (posedge AESL_clock);
        @ (posedge AESL_clock);
        @ (posedge AESL_clock);
        $finish;
    end
    
initial begin
    AESL_clock = 0;
    forever #`AUTOTB_CLOCK_PERIOD_DIV2 AESL_clock = ~AESL_clock;
end

initial begin : gen_com_proc
    integer fp;
    reg [127  : 0] token;
    reg [127  : 0] token_transaction_idx;
    integer get_com_int;
    integer i;
    integer n_wrapc;
    integer n_wrapc_pc;
    integer ret;

    n_wrapc = 0;
    n_wrapc_pc = 0;
    while(1) begin
        @(posedge AESL_clock)
        if(AESL_done_delay2 === 1 && n_wrapc_pc < AUTOTB_TRANSACTION_NUM) begin
            fp =$fopen("../wrapc_pc/com_wrapc_pc.tcl","w");
            while(fp == 0) begin
                $fclose(fp);
                fp =$fopen("../wrapc_pc/com_wrapc_pc.tcl","w");
            end
            $fdisplay(fp,"set trans_num_wrapc_pc %0d\n", n_wrapc_pc);
            $fclose(fp);
            n_wrapc_pc = n_wrapc_pc + 1;
        end
        if(ready_wire === 1 && n_wrapc < AUTOTB_TRANSACTION_NUM ) begin
            fp =$fopen("../wrapc_tv/com_rtl_ready.tcl","w");
            while(fp == 0) begin
                $fclose(fp);
                fp =$fopen("../wrapc_tv/com_rtl_ready.tcl","w");
            end
            $fdisplay(fp,"set trans_num_rtl %0d\n", n_wrapc);
            $fclose(fp);
            n_wrapc = n_wrapc + 1;
        end
        # 0.19;
        if(ready_wire === 1 && n_wrapc < AUTOTB_TRANSACTION_NUM ) begin
            fp =$fopen("../wrapc_tv/com_wrapc.tcl","r");
            while(fp == 0) begin
                $fclose(fp);
                fp =$fopen("../wrapc_tv/com_wrapc.tcl","r");
            end
               read_token(fp, token);
               read_token(fp, token);
               read_token(fp, token_transaction_idx);
            ret = $sscanf(token_transaction_idx, "%d", get_com_int);
              while (token != "trans_num_wrapc" || ret != 1 || get_com_int < n_wrapc) begin
                $fclose(fp);
                fp =$fopen("../wrapc_tv/com_wrapc.tcl","r");
                while(fp == 0) begin
                    $fclose(fp);
                    fp =$fopen("../wrapc_tv/com_wrapc.tcl","r");
                end
                   read_token(fp, token);
                   read_token(fp, token);
                   read_token(fp, token_transaction_idx);
                ret = $sscanf(token_transaction_idx, "%d", get_com_int);
            end
            $fclose(fp);
        end

    end
end

reg end_out_V_data_V;
reg [31:0] size_out_V_data_V;
reg [31:0] size_out_V_data_V_backup;
reg end_out_V_keep_V;
reg [31:0] size_out_V_keep_V;
reg [31:0] size_out_V_keep_V_backup;
reg end_out_V_strb_V;
reg [31:0] size_out_V_strb_V;
reg [31:0] size_out_V_strb_V_backup;
reg end_out_V_user_V;
reg [31:0] size_out_V_user_V;
reg [31:0] size_out_V_user_V_backup;
reg end_out_V_last_V;
reg [31:0] size_out_V_last_V;
reg [31:0] size_out_V_last_V_backup;
reg end_out_V_id_V;
reg [31:0] size_out_V_id_V;
reg [31:0] size_out_V_id_V_backup;
reg end_out_V_dest_V;
reg [31:0] size_out_V_dest_V;
reg [31:0] size_out_V_dest_V_backup;
reg end_in_V_data_V;
reg [31:0] size_in_V_data_V;
reg [31:0] size_in_V_data_V_backup;
reg end_in_V_keep_V;
reg [31:0] size_in_V_keep_V;
reg [31:0] size_in_V_keep_V_backup;
reg end_in_V_strb_V;
reg [31:0] size_in_V_strb_V;
reg [31:0] size_in_V_strb_V_backup;
reg end_in_V_user_V;
reg [31:0] size_in_V_user_V;
reg [31:0] size_in_V_user_V_backup;
reg end_in_V_last_V;
reg [31:0] size_in_V_last_V;
reg [31:0] size_in_V_last_V_backup;
reg end_in_V_id_V;
reg [31:0] size_in_V_id_V;
reg [31:0] size_in_V_id_V_backup;
reg end_in_V_dest_V;
reg [31:0] size_in_V_dest_V;
reg [31:0] size_in_V_dest_V_backup;
reg end_test_init_arr_V;
reg [31:0] size_test_init_arr_V;
reg [31:0] size_test_init_arr_V_backup;

initial begin : initial_process
    integer proc_rand;
    rst = 0;
    # 100;
    repeat(3) @ (posedge AESL_clock);
    rst = 1;
end
initial begin : start_process
    integer proc_rand;
    reg [31:0] start_cnt;
    ce = 1;
    start = 0;
    start_cnt = 0;
    wait (AESL_reset === 1);
    @ (posedge AESL_clock);
    #0 start = 1;
    start_cnt = start_cnt + 1;
    forever begin
        @ (posedge AESL_clock);
        if (start_cnt >= AUTOTB_TRANSACTION_NUM) begin
            // keep pushing garbage in
            #0 start = 1;
        end
        if (AESL_ready) begin
            start_cnt = start_cnt + 1;
        end
    end
end

always @(AESL_done)
begin
    tb_continue = AESL_done;
end

initial begin : ready_initial_process
    ready_initial = 0;
    wait (AESL_start === 1);
    ready_initial = 1;
    @(posedge AESL_clock);
    ready_initial = 0;
end

always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
      AESL_ready_delay = 0;
  else
      AESL_ready_delay = AESL_ready;
end
initial begin : ready_last_n_process
  ready_last_n = 1;
  wait(ready_cnt == AUTOTB_TRANSACTION_NUM)
  @(posedge AESL_clock);
  ready_last_n <= 0;
end

always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
      ready_delay_last_n = 0;
  else
      ready_delay_last_n <= ready_last_n;
end
assign ready = (ready_initial | AESL_ready_delay);
assign ready_wire = ready_initial | AESL_ready_delay;
initial begin : done_delay_last_n_process
  done_delay_last_n = 1;
  while(done_cnt < AUTOTB_TRANSACTION_NUM)
      @(posedge AESL_clock);
  # 0.1;
  done_delay_last_n = 0;
end

always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
  begin
      AESL_done_delay <= 0;
      AESL_done_delay2 <= 0;
  end
  else begin
      AESL_done_delay <= AESL_done & done_delay_last_n;
      AESL_done_delay2 <= AESL_done_delay;
  end
end
always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
      interface_done = 0;
  else begin
      # 0.01;
      if(ready === 1 && ready_cnt > 0 && ready_cnt < AUTOTB_TRANSACTION_NUM)
          interface_done = 1;
      else if(AESL_done_delay === 1 && done_cnt == AUTOTB_TRANSACTION_NUM)
          interface_done = 1;
      else
          interface_done = 0;
  end
end

////////////////////////////////////////////
// progress and performance
////////////////////////////////////////////

task wait_start();
    while (~AESL_start) begin
        @ (posedge AESL_clock);
    end
endtask

reg [31:0] clk_cnt = 0;
reg AESL_ready_p1;
reg AESL_start_p1;

always @ (posedge AESL_clock) begin
    clk_cnt <= clk_cnt + 1;
    AESL_ready_p1 <= AESL_ready;
    AESL_start_p1 <= AESL_start;
end

reg [31:0] start_timestamp [0:AUTOTB_TRANSACTION_NUM - 1];
reg [31:0] start_cnt;
reg [31:0] ready_timestamp [0:AUTOTB_TRANSACTION_NUM - 1];
reg [31:0] ap_ready_cnt;
reg [31:0] finish_timestamp [0:AUTOTB_TRANSACTION_NUM - 1];
reg [31:0] finish_cnt;
event report_progress;

initial begin
    start_cnt = 0;
    finish_cnt = 0;
    ap_ready_cnt = 0;
    wait (AESL_reset == 1);
    wait_start();
    start_timestamp[start_cnt] = clk_cnt;
    start_cnt = start_cnt + 1;
    if (AESL_done) begin
        finish_timestamp[finish_cnt] = clk_cnt;
        finish_cnt = finish_cnt + 1;
    end
    -> report_progress;
    forever begin
        @ (posedge AESL_clock);
        if (start_cnt < AUTOTB_TRANSACTION_NUM) begin
            if ((AESL_start && AESL_ready_p1)||(AESL_start && ~AESL_start_p1)) begin
                start_timestamp[start_cnt] = clk_cnt;
                start_cnt = start_cnt + 1;
            end
        end
        if (ap_ready_cnt < AUTOTB_TRANSACTION_NUM) begin
            if (AESL_start_p1 && AESL_ready_p1) begin
                ready_timestamp[ap_ready_cnt] = clk_cnt;
                ap_ready_cnt = ap_ready_cnt + 1;
            end
        end
        if (finish_cnt < AUTOTB_TRANSACTION_NUM) begin
            if (AESL_done) begin
                finish_timestamp[finish_cnt] = clk_cnt;
                finish_cnt = finish_cnt + 1;
            end
        end
        -> report_progress;
    end
end

reg [31:0] progress_timeout;

initial begin : simulation_progress
    real intra_progress;
    wait (AESL_reset == 1);
    progress_timeout = PROGRESS_TIMEOUT;
    $display("////////////////////////////////////////////////////////////////////////////////////");
    $display("// Inter-Transaction Progress: Completed Transaction / Total Transaction");
    $display("// Intra-Transaction Progress: Measured Latency / Latency Estimation * 100%%");
    $display("//");
    $display("// RTL Simulation : \"Inter-Transaction Progress\" [\"Intra-Transaction Progress\"] @ \"Simulation Time\"");
    $display("////////////////////////////////////////////////////////////////////////////////////");
    print_progress();
    while (finish_cnt < AUTOTB_TRANSACTION_NUM) begin
        @ (report_progress);
        if (finish_cnt < AUTOTB_TRANSACTION_NUM) begin
            if (AESL_done) begin
                print_progress();
                progress_timeout = PROGRESS_TIMEOUT;
            end else begin
                if (progress_timeout == 0) begin
                    print_progress();
                    progress_timeout = PROGRESS_TIMEOUT;
                end else begin
                    progress_timeout = progress_timeout - 1;
                end
            end
        end
    end
    print_progress();
    $display("////////////////////////////////////////////////////////////////////////////////////");
    calculate_performance();
end

task get_intra_progress(output real intra_progress);
    begin
        if (start_cnt > finish_cnt) begin
            intra_progress = clk_cnt - start_timestamp[finish_cnt];
        end else if(finish_cnt > 0) begin
            intra_progress = LATENCY_ESTIMATION;
        end else begin
            intra_progress = 0;
        end
        intra_progress = intra_progress / LATENCY_ESTIMATION;
    end
endtask

task print_progress();
    real intra_progress;
    begin
        if (LATENCY_ESTIMATION > 0) begin
            get_intra_progress(intra_progress);
            $display("// RTL Simulation : %0d / %0d [%2.2f%%] @ \"%0t\"", finish_cnt, AUTOTB_TRANSACTION_NUM, intra_progress * 100, $time);
        end else begin
            $display("// RTL Simulation : %0d / %0d [n/a] @ \"%0t\"", finish_cnt, AUTOTB_TRANSACTION_NUM, $time);
        end
    end
endtask

task calculate_performance();
    integer i;
    integer fp;
    reg [31:0] latency [0:AUTOTB_TRANSACTION_NUM - 1];
    reg [31:0] latency_min;
    reg [31:0] latency_max;
    reg [31:0] latency_total;
    reg [31:0] latency_average;
    reg [31:0] interval [0:AUTOTB_TRANSACTION_NUM - 2];
    reg [31:0] interval_min;
    reg [31:0] interval_max;
    reg [31:0] interval_total;
    reg [31:0] interval_average;
    begin
        latency_min = -1;
        latency_max = 0;
        latency_total = 0;
        interval_min = -1;
        interval_max = 0;
        interval_total = 0;

        for (i = 0; i < AUTOTB_TRANSACTION_NUM; i = i + 1) begin
            // calculate latency
            latency[i] = finish_timestamp[i] - start_timestamp[i];
            if (latency[i] > latency_max) latency_max = latency[i];
            if (latency[i] < latency_min) latency_min = latency[i];
            latency_total = latency_total + latency[i];
            // calculate interval
            if (AUTOTB_TRANSACTION_NUM == 1) begin
                interval[i] = 0;
                interval_max = 0;
                interval_min = 0;
                interval_total = 0;
            end else if (i < AUTOTB_TRANSACTION_NUM - 1) begin
                interval[i] = start_timestamp[i + 1] - start_timestamp[i];
                if (interval[i] > interval_max) interval_max = interval[i];
                if (interval[i] < interval_min) interval_min = interval[i];
                interval_total = interval_total + interval[i];
            end
        end

        latency_average = latency_total / AUTOTB_TRANSACTION_NUM;
        if (AUTOTB_TRANSACTION_NUM == 1) begin
            interval_average = 0;
        end else begin
            interval_average = interval_total / (AUTOTB_TRANSACTION_NUM - 1);
        end

        fp = $fopen(`AUTOTB_LAT_RESULT_FILE, "w");

        $fdisplay(fp, "$MAX_LATENCY = \"%0d\"", latency_max);
        $fdisplay(fp, "$MIN_LATENCY = \"%0d\"", latency_min);
        $fdisplay(fp, "$AVER_LATENCY = \"%0d\"", latency_average);
        $fdisplay(fp, "$MAX_THROUGHPUT = \"%0d\"", interval_max);
        $fdisplay(fp, "$MIN_THROUGHPUT = \"%0d\"", interval_min);
        $fdisplay(fp, "$AVER_THROUGHPUT = \"%0d\"", interval_average);

        $fclose(fp);

        fp = $fopen(`AUTOTB_PER_RESULT_TRANS_FILE, "w");

        $fdisplay(fp, "%20s%16s%16s", "", "latency", "interval");
        if (AUTOTB_TRANSACTION_NUM == 1) begin
            i = 0;
            $fdisplay(fp, "transaction%8d:%16d%16d", i, latency[i], interval[i]);
        end else begin
            for (i = 0; i < AUTOTB_TRANSACTION_NUM; i = i + 1) begin
                if (i < AUTOTB_TRANSACTION_NUM - 1) begin
                    $fdisplay(fp, "transaction%8d:%16d%16d", i, latency[i], interval[i]);
                end else begin
                    $fdisplay(fp, "transaction%8d:%16d               x", i, latency[i]);
                end
            end
        end

        $fclose(fp);
    end
endtask


////////////////////////////////////////////
// Dependence Check
////////////////////////////////////////////

`ifndef POST_SYN

`endif

AESL_deadlock_detector deadlock_detector(
    .reset(AESL_reset),
    .clock(AESL_clock));


endmodule
